# -*- coding: utf-8 -*-
"""Task3_Chatbot_NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Htc8gVjzJOT6ICCJacf4LGf2EPaoXx0j
"""

!pip install nltk

import nltk

nltk.download('punkt')

import nltk

# Download required tokenizer files
nltk.download('punkt')
nltk.download('punkt_tab')

import nltk
from nltk.tokenize import word_tokenize

print("🤖 Chatbot Started!")
print("Type 'exit' to stop")

while True:

    user_input = input("You: ").lower()

    if user_input == "exit":
        print("Chatbot: Goodbye! 👋")
        break

    tokens = word_tokenize(user_input)

    if "hello" in tokens:
        print("Chatbot: Hello! How can I help you?")

    elif "hi" in tokens:
        print("Chatbot: Hi there!")

    elif "name" in tokens:
        print("Chatbot: I am an NLP Chatbot.")

    elif "python" in tokens:
        print("Chatbot: Python is a powerful programming language.")

    elif "weather" in tokens:
        print("Chatbot: You can check weather using APIs.")

    elif "bye" in tokens:
        print("Chatbot: Goodbye! Have a nice day.")
        break

    else:
        print("Chatbot: Sorry, I don't understand.")