# -*- coding: utf-8 -*-
"""Task4_ML_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sgNM6VhohRmstWqygVzxm_kXBrSF_G9N
"""

!pip install scikit-learn pandas

import pandas as pd

data = {
    "message": [
        "Win money now",
        "Hello friend",
        "Free gift offer",
        "Meeting tomorrow",
        "Earn cash fast",
        "Let's have lunch",
        "Congratulations you won",
        "Project discussion today"
    ],

    "label": [
        "spam",
        "ham",
        "spam",
        "ham",
        "spam",
        "ham",
        "spam",
        "ham"
    ]
}

df = pd.DataFrame(data)

df

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(df["message"])

y = df["label"]

print("Text converted into numbers!")

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)

print("Data split successfully!")

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train, y_train)

print("Model trained successfully!")

predictions = model.predict(X_test)

print("Predictions:")
print(predictions)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions)

print("Model Accuracy:", accuracy)

sample_message = ["Free money offer"]

sample_vector = vectorizer.transform(sample_message)

result = model.predict(sample_vector)

print("Message:", sample_message[0])
print("Prediction:", result[0])