# -*- coding: utf-8 -*-
"""Task1_API_Visualization.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L5gmS5aocIQxD6TDPPENZqnY_T_jHeO-
"""

!pip install requests matplotlib

import requests

API_KEY = "6a7f2e999bac54152100eb4224722df6"

city = "Bangalore"

url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"

response = requests.get(url)

data = response.json()

print(data)

import requests

API_KEY = "6a7f2e999bac54152100eb4224722df6"

city = "Bangalore"

url = f"http://api.openweathermap.org/data/2.5/forecast?q={city}&appid={API_KEY}&units=metric"

response = requests.get(url)

data = response.json()

temperatures = []
dates = []

# Check API response
if "list" not in data:
    print("API Error:")
    print(data)

else:
    for item in data["list"][:8]:
        temperatures.append(item["main"]["temp"])
        dates.append(item["dt_txt"])

    print("Weather data fetched successfully!")

import matplotlib.pyplot as plt

plt.figure()

plt.plot(dates, temperatures)

plt.xticks(rotation=90)

plt.title("Temperature Forecast for Bangalore")

plt.xlabel("Date")

plt.ylabel("Temperature (°C)")

plt.tight_layout()

plt.show()