# -*- coding: utf-8 -*-
"""Task2_PDF_Report.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-31OzKQ4mE_wz0-TavH4qLCvBpQCYCFN
"""

!pip install pandas fpdf

import pandas as pd

data = {
    "Product": ["Product A", "Product B", "Product C", "Product D"],
    "Sales": [200, 350, 150, 400]
}

df = pd.DataFrame(data)

df.to_csv("sales_data.csv", index=False)

print("CSV file created successfully!")

import pandas as pd

# Read CSV file
df = pd.read_csv("sales_data.csv")

# Display data
print(df)

# Calculate total sales
total_sales = df["Sales"].sum()

# Calculate average sales
average_sales = df["Sales"].mean()

print("Total Sales:", total_sales)
print("Average Sales:", average_sales)

from fpdf import FPDF

pdf = FPDF()

pdf.add_page()

pdf.set_font("Arial", size=12)

# Title
pdf.cell(200, 10, txt="Sales Report", ln=True, align="C")

pdf.ln(10)

# Add table data
for index, row in df.iterrows():
    text = f"{row['Product']} : {row['Sales']}"
    pdf.cell(200, 10, txt=text, ln=True)

pdf.ln(10)

# Add summary
pdf.cell(200, 10, txt=f"Total Sales: {total_sales}", ln=True)

pdf.cell(200, 10, txt=f"Average Sales: {average_sales}", ln=True)

# Save PDF
pdf.output("sales_report.pdf")

print("PDF created successfully!")

import matplotlib.pyplot as plt

plt.bar(df["Product"], df["Sales"])

plt.title("Sales by Product")
plt.xlabel("Product")
plt.ylabel("Sales")

plt.savefig("sales_chart.png")

plt.show()

from fpdf import FPDF

pdf = FPDF()

pdf.add_page()

pdf.set_font("Arial", size=12)

pdf.cell(200, 10, txt="Sales Report", ln=True, align="C")

pdf.ln(10)

for index, row in df.iterrows():
    text = f"{row['Product']} : {row['Sales']}"
    pdf.cell(200, 10, txt=text, ln=True)

pdf.ln(10)

pdf.cell(200, 10, txt=f"Total Sales: {total_sales}", ln=True)

pdf.ln(10)

# Add image
pdf.image("sales_chart.png", x=10, w=100)

pdf.output("sales_report_with_chart.pdf")

print("PDF with chart created!")